# Generated by Django 5.1.7 on 2025-03-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=300, unique=True)),
                ("senha", models.CharField(max_length=30)),
                ("data_criacao", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anotacao", models.CharField(max_length=3000)),
                ("concluido", models.BooleanField(default=False)),
                (
                    "descricao",
                    models.CharField(default="Não tem descrição", max_length=200),
                ),
                ("prioridade", models.IntegerField(default=1)),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
    ]
