# Generated by Django 5.1.7 on 2025-03-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="senha",
            field=models.CharField(max_length=100),
        ),
    ]
