# Generated by Django 5.1.7 on 2025-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_senha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="senha",
            field=models.CharField(max_length=129),
        ),
    ]
